package uk.co.renbinden.alakajam.conversation

enum class ConversationFlag {

    TEDDY_BEAR_RETRIEVED_FOR_CHILD,
    LEGO_BRICK_RETRIEVED_FOR_CHILD,
    PUZZLE_PIECE_RETRIEVED_FOR_CHILD,
    PUZZLE_PIECE_RETRIEVED_FOR_GIRLFRIEND,
    SMARTPHONE_RETRIEVED_FOR_GIRLFRIEND,
    RING_RETRIEVED_FOR_GIRLFRIEND,
    GOOD_ORB_RETRIEVED_FOR_WIZARD,
    BAD_ORB_RETRIEVED_FOR_WIZARD,
    STATIC_ORB_RETRIEVED_FOR_WIZARD,
    CHALICE_RETRIEVED_FOR_PIRATE,
    RING_RETRIEVED_FOR_PIRATE,
    GEMS_RETRIEVED_FOR_PIRATE,
    TREASURE_CHEST_RETRIEVED_FOR_PIRATE,
    GOOD_ORB_RETRIEVED_FOR_PIRATE,
    BAD_ORB_RETRIEVED_FOR_PIRATE,
    STATIC_ORB_RETRIEVED_FOR_PIRATE,
    CROWN_RETRIEVED_FOR_PIRATE

}